apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-app
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-app
    spec:
      containers:
      - image: ahmedcherif37/app-etudiant-python:1.0.0
        name: app-etudiant-python
        ports:
        - containerPort: 5000
        resources: {}
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: conf-app
              key:  MYSQL_HOST
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: conf-app
              key:  MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  secret-mysql
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: conf-app
              key: MYSQL_DATABASE
status: {}
